#!/bin/bash
cp implementation/system.bit ../bit_files/roach2_tut_intro_2019_Aug_27_1633.bit
./mkbof_64 -o implementation/system.bof -s core_info.tab -t 3 implementation/system.bin
cp implementation/system.bof ../bit_files/roach2_tut_intro_2019_Aug_27_1633.bof
cp design_info.tab ../bit_files/roach2_tut_intro_2019_Aug_27_1633.info
gzip -c ../bit_files/roach2_tut_intro_2019_Aug_27_1633.bof  > ../bit_files/roach2_tut_intro_2019_Aug_27_1633.bof.gz
gzip -c implementation/system.bin > implementation/system.bin.gz
cat implementation/system.bin.gz >> /home/ulloaroach2/design/tut_intro/roach2_tut_intro/XPS_ROACH2_base/extended_info.kcpfpg
cp extended_info.kcpfpg ../bit_files/roach2_tut_intro_2019_Aug_27_1633.fpg
