#!/bin/bash
cp implementation/system.bit ../bit_files/snapshot_roach2_2019_Sep_02_1022.bit
./mkbof_64 -o implementation/system.bof -s core_info.tab -t 3 implementation/system.bin
cp implementation/system.bof ../bit_files/snapshot_roach2_2019_Sep_02_1022.bof
cp design_info.tab ../bit_files/snapshot_roach2_2019_Sep_02_1022.info
gzip -c ../bit_files/snapshot_roach2_2019_Sep_02_1022.bof  > ../bit_files/snapshot_roach2_2019_Sep_02_1022.bof.gz
gzip -c implementation/system.bin > implementation/system.bin.gz
cat implementation/system.bin.gz >> /home/ulloaroach2/design/test_adc/snapshot_roach2/XPS_ROACH2_base/extended_info.kcpfpg
cp extended_info.kcpfpg ../bit_files/snapshot_roach2_2019_Sep_02_1022.fpg
